### ISSUE TITLE
Wrong data for AVC version checking

### ISSUE THREAD

**Issue by bfrobin446** [inigmatus/ContractPack-SoundingRockets#3]
The "URL" entry in SoundingRockets.version currently directs the version checker to download the current version's info from https://github.com/inigmatus/ContractPack-SoundingRockets/blob/master/SoundingRockets.version . The version checker isn't smart enough to find the actual contents of the version file in that HTML view, so you'll need to link to the raw version of the file: https://raw.githubusercontent.com/inigmatus/ContractPack-SoundingRockets/master/SoundingRockets.version .

It would also be a good idea to change the GitHub "REPOSITORY" from "GAP" to "ContractPack-SoundingRockets" so version checkers that want to talk to GitHub end up at the right repository.

**Comment by inigma2** [comment]
fixed.
